---
# handlers file for frontend-build
---
# tasks file for frontend-build
- name: Installing npm package 
  apt:
    name: npm
    state: present
  become: true

- name: Installing Curl package 
  apt:
    name: curl
    state: present
  become: true

- name: Add Yarn GPG Key
  shell: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  become: true

- name: add Yarn Repository
  shell: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  become: true

- name: Install Yarn
  apt:
    name: yarn
    state: latest
  become: true

- name: Add safe directory to git
  community.general.git_config:
    name: safe.directory
    value: 
      - /var/www/fe-todo
    scope: global

- name: Clone frontend repository
  git:
    repo: https://github.com/elshiraphine/fe-todo.git
    dest: /etc/www/fe-todo
    version: main
    force: yes

- name: Change permissions 1
  file:
    path: /var/www/fe-todo
    mode: '0777'
    recurse: yes
  become: true

# - name: Add NodeSource Repository
#   shell: |
#     curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
#     sudo apt-get update
#   args:
#     chdir: /home/reivertt

# - name: Install Node.js
#   apt:
#     name: nodejs
#     state: present
#   become: true

- name: Install NVM
  become: yes  
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash

- name: Source NVM for immediate availability 
  become: yes
  shell: . /root/.nvm/nvm.sh  

- name: Install Node.js version 18
  become: yes
  shell: . /root/.nvm/nvm.sh && nvm install 18

- name: Set Node.js version 18 as default
  become: yes
  shell: . /root/.nvm/nvm.sh && nvm use 18

- name: Install pm2 globally
  shell: sudo npm install pm2 -g
  become: true

- name: Install dependencies and build
  shell: |
    yarn install --ignore-engines
    yarn build
  args:
    chdir: /etc/www/fe-todo
  become: yes

- name: Start Pm2
  shell: pm2 start --name fe-todo "yarn start"
  args: 
    chdir: /etc/www/fe-todo 

