---
# tasks file for frontend-deploy
- name: Start Pm2
  shell: source $HOME/.nvm/nvm.sh && cd /var/www/fe-todo &&  pm2 start --name fe-todo "yarn start"
  args: 
    executable: /bin/bash

- name: Create nginx configuration
  copy:
    src: templates/fe-todo.j2
    dest: /etc/nginx/sites-available/fe-todo 

- name: Link nginx configuration
  file:
    src: /etc/nginx/sites-available/fe-todo
    dest: /etc/nginx/sites-enabled/fe-todo
    state: link
  become: true
  notify: Restart nginx

- name: Check results
  uri: 
    url: "http://localhost:3000"
    method: GET
    return_content: yes
  register: res

- name: Show nginx result
  debug:
    var: res.content