---
# tasks file for backend-deploy
- name: Copy be template
  become: true
  copy:
    src: templates/be-template.j2
    dest: /etc/nginx/sites-available/backend

- name: Link to sites-enabled
  file: 
    src: /etc/nginx/sites-available/backend
    dest: /etc/nginx/sites-enabled/backend
    state: link
  become: true