---
# tasks file for frontend-build
- name: Install NVM
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    source ~/.bashrc
  args:
    chdir: /home/reivertt

- name: Install Yarn
  apt:
    name: yarn
    state: latest

- name: Add safe directory to git
  community.general.git_config:
    name: safe.directory
    value: 
      - /var/www/fe-todo
    scope: global

- name: Clone frontend repository
  git:
    repo: https://github.com/elshiraphine/fe-todo.git
    dest: /etc/www/fe-todo
    version: master
    force: yes

- name: Change permissions 1
  file:
    path: /var/www/fe-todo
    mode: '0777'
    recurse: yes
  become: true

- name: Install Node.js 18
  shell: |
    sudo nvm install 18
    sudo nvm alias default 18
  args:
    chdir: /home/reivertt

- name: Install pm2
  apt:
    name: npm
    state: latest

- name: Install pm2 globally
  npm:
    name: pm2
    global: yes

- name: Set up pm2
  shell: |
    cd /etc/www/fe-todo
    yarn install --ignore-engines && yarn build
    pm2 start --name fe-todo "yarn start"
  args:
    user: reivertt

